import type { Prisma } from '@prisma/client';
import { prisma } from '@cornermaximo/db';
import type { Metadata } from 'next';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { createClient } from '@/lib/supabase/server';

export const metadata: Metadata = { title: 'Mi Corner', description: 'Tu centro personal de seguimiento, favoritos, partidos, alertas y watchlists en CornerMaximo.', robots: { index: false, follow: false } };
type FavoriteRow={kind:'player'|'team'|'competition';entity_slug:string;display_name:string;image_url:string|null;subtitle:string|null};
type WatchlistPlayerRow={player_slug:string};
type TrackedPlayer={slug:string;fullName:string;knownAs:string|null;photoUrl:string|null;status:string;currentTeam:{name:string;slug:string;crestUrl:string|null}|null};
type UpcomingMatch={id:number;kickoffAt:Date;round:string|null;season:{competition:{name:string;slug:string}};teams:Array<{isHome:boolean;team:{name:string;slug:string;crestUrl:string|null}}>};
const STATUS_LABEL:Record<string,string>={AVAILABLE:'Disponible',INJURED:'Lesionado',SUSPENDED:'Sancionado',DOUBT:'Duda',NOT_CALLED:'No convocado'};
const STATUS_CLASS:Record<string,string>={AVAILABLE:'border-pitch-accent/30 bg-pitch-accent/10 text-pitch-accent',INJURED:'border-pitch-danger/30 bg-pitch-danger/10 text-pitch-danger',SUSPENDED:'border-pitch-warning/30 bg-pitch-warning/10 text-pitch-warning',DOUBT:'border-pitch-warning/30 bg-pitch-warning/10 text-pitch-warning',NOT_CALLED:'border-pitch-border bg-pitch-elevated text-pitch-muted'};
function formatKickoff(date:Date){return new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Madrid'}).format(date)}
export default async function MyCornerPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/auth/login?next=/mi-corner');
 const [favoritesResult,watchlistsResult,recentListsResult,watchlistPlayersResult]=await Promise.all([
  supabase.from('user_favorites').select('kind,entity_slug,display_name,image_url,subtitle').eq('user_id',user.id),
  supabase.from('user_watchlists').select('id',{count:'exact',head:true}).eq('user_id',user.id),
  supabase.from('user_watchlists').select('id,name,description,updated_at').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(3),
  supabase.from('user_watchlist_players').select('player_slug').eq('user_id',user.id).limit(100)]);
 const rows=(favoritesResult.data??[]) as FavoriteRow[]; const wp=(watchlistPlayersResult.data??[]) as WatchlistPlayerRow[];
 const pf=rows.filter(r=>r.kind==='player'),tf=rows.filter(r=>r.kind==='team'),cf=rows.filter(r=>r.kind==='competition');
 const playerSlugs=[...new Set([...pf.map(r=>r.entity_slug),...wp.map(r=>r.player_slug)])].slice(0,30); const teamSlugs=[...new Set(tf.map(r=>r.entity_slug))].slice(0,20); const compSlugs=[...new Set(cf.map(r=>r.entity_slug))].slice(0,20);
 let players:TrackedPlayer[]=[],matches:UpcomingMatch[]=[],sportsError=false;
 try{players=playerSlugs.length?await prisma.player.findMany({where:{slug:{in:playerSlugs}},orderBy:[{status:'asc'},{fullName:'asc'}],take:8,select:{slug:true,fullName:true,knownAs:true,photoUrl:true,status:true,currentTeam:{select:{name:true,slug:true,crestUrl:true}}}}):[]; const related=[...new Set([...teamSlugs,...players.flatMap(p=>p.currentTeam?[p.currentTeam.slug]:[])])]; const or:Prisma.MatchWhereInput[]=[]; if(related.length)or.push({teams:{some:{team:{slug:{in:related}}}}});if(compSlugs.length)or.push({season:{competition:{slug:{in:compSlugs}}}});matches=or.length?await prisma.match.findMany({where:{status:'SCHEDULED',kickoffAt:{gte:new Date()},OR:or},orderBy:{kickoffAt:'asc'},take:6,select:{id:true,kickoffAt:true,round:true,season:{select:{competition:{select:{name:true,slug:true}}}},teams:{select:{isHome:true,team:{select:{name:true,slug:true,crestUrl:true}}}}}}):[]}catch{sportsError=true}
 const watchlistCount=watchlistsResult.count??0,recentLists=recentListsResult.data??[],personalError=Boolean(favoritesResult.error||watchlistsResult.error||recentListsResult.error||watchlistPlayersResult.error),attention=players.filter(p=>p.status!=='AVAILABLE').length;
 return <div className="space-y-8"><Breadcrumbs items={[{label:'Mi Corner'}]}/>
 <header className="relative overflow-hidden rounded-2xl border border-pitch-border bg-pitch-card/80 p-5 sm:p-7"><div aria-hidden="true" className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-pitch-accent/10 blur-3xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="fs-eyebrow">CORNERMAXIMO · TU ESPACIO</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Mi Corner</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-pitch-muted">Tu seguimiento deportivo en una sola pantalla: próximos partidos, jugadores, favoritos, watchlists y señales que requieren atención.</p></div><div className="flex flex-wrap gap-2"><Link href="/watchlists" className="fs-btn-primary">Nueva watchlist</Link><Link href="/scouting" className="fs-btn-ghost">Abrir CM Scout</Link></div></div></header>
 {(personalError||sportsError)&&<p role="alert" className="rounded-xl border border-pitch-warning/40 bg-pitch-warning/10 px-4 py-3 text-sm text-pitch-warning">Parte de Mi Corner no se pudo actualizar. Tus datos personales siguen protegidos y puedes continuar usando CornerMaximo.</p>}
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" aria-label="Resumen de Mi Corner">{[{label:'Jugadores',value:pf.length,href:'/favoritos'},{label:'Equipos',value:tf.length,href:'/favoritos'},{label:'Competiciones',value:cf.length,href:'/favoritos'},{label:'Watchlists',value:watchlistCount,href:'/watchlists'},{label:'Atención',value:attention,href:'#jugadores-seguidos'}].map(c=><Link key={c.label} href={c.href} className="fs-panel-interactive p-4 sm:p-5"><p className="text-xs font-semibold uppercase tracking-wide text-pitch-muted">{c.label}</p><p className="mt-2 font-display text-3xl font-bold tabular-nums text-white">{c.value}</p></Link>)}</section>
 <section className="fs-panel p-5 sm:p-6"><div className="flex items-end justify-between gap-4"><div><p className="fs-eyebrow">HOY · TU AGENDA</p><h2 className="mt-1 text-2xl font-bold">Próximos partidos</h2></div><Link href="/partidos" className="text-sm font-semibold text-pitch-accent">Ver calendario</Link></div>{matches.length?<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{matches.map(m=>{const h=m.teams.find(t=>t.isHome)?.team,a=m.teams.find(t=>!t.isHome)?.team;return <Link key={m.id} href={`/partidos/${m.id}`} className="rounded-xl border border-pitch-border bg-pitch-bg/50 p-4 transition hover:border-pitch-accent/40"><div className="flex justify-between gap-3 text-xs text-pitch-muted"><span className="truncate">{m.season.competition.name}</span><time dateTime={m.kickoffAt.toISOString()}>{formatKickoff(m.kickoffAt)}</time></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] gap-2 text-sm font-semibold"><span className="truncate text-right">{h?.name??'—'}</span><span className="text-pitch-muted">vs</span><span className="truncate">{a?.name??'—'}</span></div></Link>})}</div>:<div className="mt-5 rounded-xl border border-dashed border-pitch-border p-6 text-center"><p className="font-semibold">Tu agenda está vacía</p><p className="mt-2 text-sm text-pitch-muted">Añade equipos, jugadores o competiciones para personalizarla.</p><Link href="/favoritos" className="fs-btn-ghost mt-4 inline-flex">Gestionar favoritos</Link></div>}</section>
 <div className="grid gap-6 lg:grid-cols-[1.35fr_1fr]"><section id="jugadores-seguidos" className="fs-panel p-5 sm:p-6"><div className="flex justify-between"><div><p className="fs-eyebrow">SEGUIMIENTO</p><h2 className="mt-1 text-2xl font-bold">Tus jugadores</h2></div><Link href="/watchlists" className="text-sm font-semibold text-pitch-accent">Organizar</Link></div>{players.length?<div className="mt-5 grid gap-3 sm:grid-cols-2">{players.map(p=><Link key={p.slug} href={`/jugadores/${p.slug}`} className="flex items-center gap-3 rounded-xl border border-pitch-border bg-pitch-bg/50 p-3 hover:border-pitch-accent/40">{p.photoUrl?<img src={p.photoUrl} alt="" width={48} height={48} className="h-12 w-12 rounded-full object-cover"/>:<span aria-hidden="true" className="grid h-12 w-12 place-items-center rounded-full bg-pitch-elevated">CM</span>}<div className="min-w-0 flex-1"><p className="truncate font-semibold">{p.knownAs??p.fullName}</p><p className="truncate text-xs text-pitch-muted">{p.currentTeam?.name??'Sin equipo'}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] font-semibold ${STATUS_CLASS[p.status]??STATUS_CLASS.NOT_CALLED}`}>{STATUS_LABEL[p.status]??p.status}</span></Link>)}</div>:<div className="mt-5 rounded-xl border border-dashed border-pitch-border p-6 text-center"><p className="font-semibold">Empieza a seguir jugadores</p><Link href="/scouting" className="fs-btn-primary mt-4 inline-flex">Descubrir en CM Scout</Link></div>}</section>
 <section className="fs-panel p-5 sm:p-6"><p className="fs-eyebrow">SCOUTING</p><h2 className="mt-1 text-2xl font-bold">Watchlists</h2>{recentLists.length?<div className="mt-5 space-y-3">{recentLists.map(l=><Link key={l.id} href="/watchlists" className="block rounded-xl border border-pitch-border bg-pitch-bg/50 p-4 hover:border-pitch-accent/40"><p className="font-semibold">{l.name}</p><p className="mt-1 line-clamp-2 text-sm text-pitch-muted">{l.description??'Lista privada de jugadores'}</p></Link>)}</div>:<div className="mt-5 rounded-xl border border-dashed border-pitch-border p-6 text-center"><p className="font-semibold">Todavía no tienes watchlists</p><Link href="/watchlists" className="fs-btn-primary mt-4 inline-flex">Crear primera lista</Link></div>}</section></div>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Accesos rápidos">{[{href:'/favoritos',title:'Favoritos',copy:'Jugadores, equipos y competiciones.'},{href:'/comparador',title:'CM Compare',copy:'Compara los perfiles que sigues.'},{href:'/rankings',title:'Rankings',copy:'Descubre rendimiento destacado.'},{href:'/cuenta/seguridad',title:'Cuenta y seguridad',copy:'Gestiona tu cuenta CornerMaximo.'}].map(i=><Link key={i.href} href={i.href} className="fs-panel-interactive p-4"><p className="font-semibold">{i.title}</p><p className="mt-1 text-sm text-pitch-muted">{i.copy}</p></Link>)}</section></div>;
}
